/* eslint-disable import/no-anonymous-default-export */
export default [
    {
        type: "Soft Skill",
        subType: "EngX Processes",
        level: "L3",
        question: "Over- or underestimation?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "EngX Processes",
        level: "L3",
        question: "What is the main difference between good and bad technical documentation?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "EngX Processes",
        level: "L3",
        question: "Please compare a brown field and green field project.",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "EngX Processes",
        level: "L3",
        question: "What is the difference between agile and Scrum?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "EngX Processes",
        level: "L3",
        question: "Can you tell me about agile methodologies?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "EngX Processes",
        level: "L3",
        question: "Let's say you need to organize the code review process on a new project. Please describe how would you do that.",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "EngX Processes",
        level: "L3",
        question: "Define the DoD (DEFINITION OF DONE) and tell the difference between Definition of Done and Definition of Ready.",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Delegation, Task Assignment",
        level: "L4",
        question: "How can we split a user story that is too big to handle as one chunk? Do you know any special techniques?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Delegation, Task Assignment",
        level: "L3",
        question: "When and what would you escalate to whom? Have you or anyone from your team ever been escalated? If so, what was the case and how did it turn out?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Delegation, Task Assignment",
        level: "L3",
        question: "Imagine I am your subordinate. Please assign some tasks to me.",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Delegation, Task Assignment",
        level: "L3",
        question: "Delegate vs assignment?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Motivation (Self and others)",
        level: "L4",
        question: "How would you motivate a team member who seems discouraged or lacks energy?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Motivation (Self and others)",
        level: "L3",
        question: "How do you motive yourself?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Motivation (Self and others)",
        level: "L3",
        question: "How working from home changed the way you work? How did it affect the team’s dynamics and the work with the customer?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Motivation (Self and others)",
        level: "L3",
        question: "What were your biggest accomplishments and failures in this position?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Motivation (Self and others)",
        level: "L3",
        question: "What is your approach to learning?",
        answer: "",
    },
];
