/* eslint-disable import/no-anonymous-default-export */
export default [
    {
        type: "Soft Skill",
        subType: "Onboarding, Learning & Development, Mentoring",
        level: "L4",
        question: "You have some experience delivering public speech. What are the best practices of giving public speech? Which things should be avoided?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Onboarding, Learning & Development, Mentoring",
        level: "L4",
        question: "Subordinate has constant overtime, delivers in time and in quality, what are the risks? what would you do?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Onboarding, Learning & Development, Mentoring",
        level: "L3",
        question: "Let us imagine that you are interviewing candidates for your own project. What would be the traits of a good candidate? What would raise red flags? If you could only ask 3 questions from them, what would they be?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Onboarding, Learning & Development, Mentoring",
        level: "L3",
        question: "How do you communicate negative feedback to colleagues or mentees?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Onboarding, Learning & Development, Mentoring",
        level: "L3",
        question: "Describe a SMART goal you set for yourself.",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Onboarding, Learning & Development, Mentoring",
        level: "L3",
        question: "Tell me about a situation when you were asked to do something that you had never done before. How did you manage, what did you learn?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Onboarding, Learning & Development, Mentoring",
        level: "L3",
        question: "Two newbies are going to join your team and your lead asks you to onboard them, how would you approach that?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Onboarding, Learning & Development, Mentoring",
        level: "L3",
        question: "Were there cases when your mentee failed? What would you do in this case?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Onboarding, Learning & Development, Mentoring",
        level: "L3",
        question: "What do you think about mentoring? Does it have any advantages for you?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Onboarding, Learning & Development, Mentoring",
        level: "L3",
        question: "What is the difference between adaptation and onboarding? Tell us about some examples for an adaptation and onboarding plan from your experience.",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Conflict & Issue handling",
        level: "L4",
        question: "Consider a situation: You are a team-lead and one of your teammates has a negative/destructive attitude? He always demotivates others and damages the team morale. How will you handle the situation?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Conflict & Issue handling",
        level: "L4",
        question: "Have you ever made unpopular decisions? Did you manage to achieve your goal?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Conflict & Issue handling",
        level: "L3",
        question: "Suppose you have made a critical fix, but someone from your team rejected the pull request because of few clean code related issues and you do not have time to update the request. What do you do in such cases?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Conflict & Issue handling",
        level: "L3",
        question: "What do you do if there is a disagreement within your team?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Conflict & Issue handling",
        level: "L3",
        question: "How do you handle stress? Do you use any techniques?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Conflict & Issue handling",
        level: "L3",
        question: "Please describe a time when you had a miscommunication with your project manager. What was the reason for it? How did you solve it?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Conflict & Issue handling",
        level: "L3",
        question: "Can you recall a situation when you had to deny somebody at work?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Conflict & Issue handling",
        level: "L3",
        question: "What were your biggest challenge so far on the project? What was it, what did you do and how did it work out? Would you do anything differently next time? If so, what and why?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Conflict & Issue handling",
        level: "L3",
        question: "What would you do if you would be assigned to a Lead position on a project while you know that you lack the required knowledge or experience to fill that role successfully?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Conflict & Issue handling",
        level: "L3",
        question: "What would you do if you realize that one of your teammates would like to leave the company?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Negotiations / Client Communication",
        level: "L4",
        question: "How do you make sure to provide the appropriate level of transparency on the project to the customer?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Negotiations / Client Communication",
        level: "L4",
        question: "You have a backlog but not revealed to your team, the customer says all of them are high priority, all important, estimate it, not doable to complete all of them?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Negotiations / Client Communication",
        level: "L3",
        question: "How to negotiate with a client if you failed a demo (result of 2 sprints). Suppose the customers write you an agreed email after a failed demo. How would you reply?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Negotiations / Client Communication",
        level: "L3",
        question: "How will you sell code refactoring?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Negotiations / Client Communication",
        level: "L3",
        question: "Manager asks you to provide an estimate for a task which is completely unknown for you. How would you do that?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Negotiations / Client Communication",
        level: "L3",
        question: "You are the main FE person on project and customer wants you to work on weekend and offering you direct pay. What would you do?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Negotiations / Client Communication",
        level: "L3",
        question: "How would you organize communication with customer to make her/him happy?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Negotiations / Client Communication",
        level: "L3",
        question: "How would you convince the customer to choose xxx or typescript to be used on a project? ",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Negotiations / Client Communication",
        level: "L3",
        question: "What shall you do if in the middle of the sprint customer management approaches you directly and asks to shift priorities and start working on the Newly Created item outside of the sprint?",
        answer: "",
    },
    {
        type: "Soft Skill",
        subType: "Negotiations / Client Communication",
        level: "L3",
        question: "Can you describe a situation where you successfully pushed your own idea or solution in the project?",
        answer: "",
    },
];
